# Generated by Django 2.2.1 on 2019-06-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='activeLink',
            field=models.BooleanField(default=False),
        ),
    ]
