# Generated by Django 2.2.1 on 2019-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_executives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executives',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
