# Generated by Django 2.2.1 on 2019-09-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20190917_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executives',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
