# Generated by Django 2.2.1 on 2019-09-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_executives_portrait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executives',
            name='portrait',
        ),
        migrations.AddField(
            model_name='executives',
            name='imageRotation',
            field=models.CharField(choices=[('0', '0'), ('90', '90'), ('180', '180'), ('270', '270')], default='0', max_length=3),
        ),
    ]
