# Generated by Django 2.2.1 on 2019-11-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20190921_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longDistance', models.CharField(max_length=100)),
                ('shortDistance', models.CharField(blank=True, max_length=100)),
                ('picture', models.ImageField(upload_to='media/routes')),
                ('directions', models.FileField(upload_to='media/routes')),
            ],
        ),
    ]
