# Generated by Django 2.2.1 on 2019-11-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
