# Generated by Django 2.2.7 on 2019-11-27 04:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_route_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executives',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
