# Generated by Django 2.2.7 on 2019-11-27 05:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_auto_20191127_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
