# Generated by Django 2.2.7 on 2019-11-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_auto_20191127_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='directions',
            field=models.TextField(max_length=10000),
        ),
    ]
