# Generated by Django 2.2.7 on 2019-11-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20191127_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='directions',
            new_name='directionsText',
        ),
    ]
