# Generated by Django 2.2.7 on 2019-11-27 14:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_auto_20191127_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executives',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
